# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 09:38
from __future__ import unicode_literals

import accounting_entry.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart_account', '0009_auto_20160420_1355'),
        ('accounting_entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountingentry',
            name='number',
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='account_credit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chart_accaunt_credit', to='chart_account.ChartAccaunt', verbose_name='Chart Accaunt Debit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='account_debit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chart_accaunt_debit', to='chart_account.ChartAccaunt', verbose_name='Chart Accaunt Debit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='count_credit',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Count Credit'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='count_debit',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Count Debit'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='sum_credit',
            field=accounting_entry.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23, verbose_name='Sum Credit'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='sum_debit',
            field=accounting_entry.models.MoneyField(decimal_places=8, default=Decimal('0'), max_digits=23, verbose_name='Sum Debit'),
        ),
    ]
