# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='through',
            name='some',
        ),
    ]
