# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_account', '0004_auto_20160419_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartaccaunt',
            options={'ordering': ['number'], 'verbose_name_plural': 'Chart Accaunt Plural'},
        ),
        migrations.AlterModelOptions(
            name='chartaccauntgroup',
            options={'ordering': ['number'], 'verbose_name_plural': 'Group Accaunt Plural'},
        ),
    ]
