# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_account', '0005_auto_20160419_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartaccaunt',
            name='quantitative',
            field=models.SmallIntegerField(max_length=1, null=True, verbose_name='quantitative'),
        ),
    ]
