# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chart_account', '0006_chartaccaunt_quantitative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subconto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Unique code')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date creation')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('number', models.CharField(max_length=255, verbose_name='Number')),
            ],
            options={
                'verbose_name_plural': 'Subconto',
                'ordering': ['number'],
            },
        ),
        migrations.AlterField(
            model_name='chartaccaunt',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='chart_account.ChartAccauntGroup', verbose_name='Group Accaunt'),
        ),
        migrations.AlterField(
            model_name='chartaccaunt',
            name='quantitative',
            field=models.SmallIntegerField(choices=[('0', 'No'), ('1', 'quantitative'), ('2', 'monetary')], null=True, verbose_name='quantitative'),
        ),
        migrations.AddField(
            model_name='chartaccaunt',
            name='subconto',
            field=models.ManyToManyField(related_name='subconto', to='chart_account.Subconto'),
        ),
    ]
