# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_account', '0007_auto_20160419_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartaccaunt',
            name='active_passive',
            field=models.SmallIntegerField(choices=[('1', 'active'), ('2', 'passive'), ('3', 'active_passive')], default=7, verbose_name='Active or Passive'),
            preserve_default=False,
        ),
    ]
