# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_account', '0008_chartaccaunt_active_passive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subconto',
            options={'ordering': ['number'], 'verbose_name': 'Subconto', 'verbose_name_plural': 'Subconto'},
        ),
        migrations.AlterField(
            model_name='chartaccaunt',
            name='active_passive',
            field=models.SmallIntegerField(choices=[(1, 'active'), (2, 'passive'), (3, 'active_passive')], verbose_name='Active or Passive'),
        ),
        migrations.AlterField(
            model_name='chartaccaunt',
            name='quantitative',
            field=models.SmallIntegerField(choices=[(0, 'No'), (1, 'quantitative'), (2, 'monetary')], null=True, verbose_name='quantitative'),
        ),
    ]
