# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 13:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Unique code')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date creation')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('number', models.CharField(max_length=255, verbose_name='Number')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
