# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 13:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart_account', '0009_auto_20160420_1355'),
        ('registeres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoiceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Unique code')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date creation')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('number', models.CharField(max_length=255, verbose_name='Number')),
                ('chart_account_active', models.ManyToManyField(null=True, related_name='chart_account_actives_related', to='chart_account.ChartAccaunt', verbose_name='Chart Accaunt Active')),
                ('chart_account_passive', models.ManyToManyField(null=True, related_name='chart_account_passives_related', to='chart_account.ChartAccaunt', verbose_name='Chart Accaunt Passive')),
                ('stock_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registeres.Stock', verbose_name='Stock Register')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
